#
# application.yml
#
# This will become the base profile for the "common settings"
# All settings here may be overriden by profile-specific properties in application-{profile}.yml
# 


# Server settings
server:
  port: 8080


# app name and build version updated during build process from Maven properties.
info:
  app:
    name: '@project.artifactId@'
  build:
    version: '@project.version@'


# Logging
logging:
  level:
    root: ERROR                           # ERROR level at root
    org.springframework: INFO             # INFO level for Spring
    app: INFO                             # INFO level for application
  pattern:
    console: "==> [%p] %c{1}(%L) - %m%n"
